openapi: 3.0.0
info:
  version: 1.0.0
  title: API de la Tienda
  description: API para la gestión de productos de la Tienda
paths:
  /producto:
    get:
      tags:
        - producto
      description: Devuelve todos los productos
      operationId: getProducto
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Productos'

  /producto/{id}:
    get:
      tags:
        - producto
      description: Devuelve un recurso producto por su identificador
      operationId: getProductoByid
      parameters:
        - name: id
          in: path
          required: true
          description: El identificador del producto
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'
        '400':
          description: Datos de la petición incorrectos
        '401':
          description: No autorizado
        '404':
          description: Recurso no encontrado
    delete:
      tags:
        - producto
      description: Elimina un producto
      operationId: deleteProducto
      parameters:
        - name: id
          in: path
          description: El identificador del producto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Respuesta exitosa. Producto eliminado
        '401':
          description: No autorizado
        '404':
          description: Producto no encontrado

  /producto/{id}/solicitar:
    put:
      tags:
        - producto
      description: Solicita al almacén nuevas unidades de un producto
      operationId: putSolicitarProducto
      security:
        - ApiKeyAuth: []      
      parameters:
        - name: id
          in: path
          required: true
          description: El identificador del producto
          schema:
            type: integer
            format: int64
        - name: cantidad
          in: query
          required: true
          description: Cantidad de unidades a solicitar
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa. Unidades modificadas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'          
        '400':
          description: Datos de la petición incorrectos
        '401':
          description: No autorizado
        '404':
          description: Producto no encontrado

  /producto/{id}/vender:
    put:
      tags:
        - producto
      description: Vende unidades de un Producto dado
      operationId: putVenderProducto
      parameters:
        - name: id
          in: path
          required: true
          description: El identificador del producto
          schema:
            type: integer
            format: int64
        - name: cantidad
          in: query
          required: true
          description: Cantidad de unidadesa vender
          schema:
            type: integer
      responses:
        '200':
          description: Respuesta exitosa. Producto vendido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'          
        '400':
          description: Datos de la petición incorrectos
        '404':
          description: Producto no encontrado

  /producto/{id}/cambiar_precio:
    put:
      tags:
        - producto
      description: Vende unidades de un Producto dado
      operationId: putVenderProducto
      parameters:
        - name: id
          in: path
          required: true
          description: El identificador del producto
          schema:
            type: integer
            format: int64
        - name: precio
          in: query
          required: true
          description: Nuevo precio del producto
          schema:
            type: number
            format: float
      responses:
        '200':
          description: Respuesta exitosa. Precio modificado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Producto'          
        '400':
          description: Datos de la petición incorrectos
        '404':
          description: Producto no encontrado

components:
  securitySchemes:
    ApiKeyAuth: 
      type: apiKey
      in: header
      name: api-key-warehouse
  schemas:
    Productos:
      type: array
      items:
        $ref: '#/components/schemas/Producto'
    Producto:
      properties:
        producto_id:
          type: integer
          format: int64
          description: Identificador único del producto
        articulo_id:
          type: integer
          format: int64
          description: Identificador único del articulo del almacén
        nombre:
          type: string
          description: Nombre único del producto
        disponibles:
          type: integer
          description: Unidades disponibles
        vendidas:
          type: integer
          description: Unidades vendidas
        precio:
          type: number
          format: float
          description: Precio de venta
