name: Pipeline backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pylint
      run: pylint `find . -type f|grep .py$|xargs`
    - name: Pytest
      run: pytest `find . -type f|grep test_*.py$|xargs`
